/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package practico4.grupo14;
//ANA

import clases.Alumno;
import javax.swing.JOptionPane;

/**
 *
 * @author Candela Naranjo
 */
public class AltadeAlumnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form AltadeAlumno
     */
    public AltadeAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloFormularioAlumnos = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblLegajo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLegajo = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNombre = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtApellido = new javax.swing.JTextPane();
        btnNuevoAlumno = new javax.swing.JButton();
        btnSalirAlumno = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Formulario Alumnos");

        lblTituloFormularioAlumnos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTituloFormularioAlumnos.setText("Formulario de Alumnos");

        lblNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNombre.setText("Nombre:");

        lblApellido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblApellido.setText("Apellido:");

        lblLegajo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblLegajo.setText("Legajo:");

        jScrollPane1.setViewportView(txtLegajo);

        jScrollPane2.setViewportView(txtNombre);

        jScrollPane3.setViewportView(txtApellido);

        btnNuevoAlumno.setText("Cargar Alumno");
        btnNuevoAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoAlumnoMouseClicked(evt);
            }
        });
        btnNuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoAlumnoActionPerformed(evt);
            }
        });

        btnSalirAlumno.setText("Salir");
        btnSalirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombre)
                            .addComponent(lblLegajo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTituloFormularioAlumnos)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblApellido)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalirAlumno))
                            .addComponent(jScrollPane3))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTituloFormularioAlumnos)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLegajo)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblNombre))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblApellido)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalirAlumno)
                    .addComponent(btnNuevoAlumno))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAlumnoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirAlumnoActionPerformed

    private void btnNuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAlumnoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnNuevoAlumnoActionPerformed

    private void btnNuevoAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoAlumnoMouseClicked
        // ANA PAULA
        //carga el alumno a la lista
        try {
            int legajo = Integer.parseInt(txtLegajo.getText());
            Alumno a = new Alumno(legajo, txtApellido.getText(), txtNombre.getText());
            if (practico4.listaAlumnos.add(a)) {
                JOptionPane.showMessageDialog(this, "Alumno cargado correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error: Ya existe un alumno con ese legajo", "Error", JOptionPane.ERROR_MESSAGE);
            }
            txtLegajo.setText("");
            txtApellido.setText("");
            txtNombre.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Tipo de dato ingresado invalido", "ADVERTENCIA", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnNuevoAlumnoMouseClicked
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoAlumno;
    private javax.swing.JButton btnSalirAlumno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblLegajo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTituloFormularioAlumnos;
    private javax.swing.JTextPane txtApellido;
    private javax.swing.JTextPane txtLegajo;
    private javax.swing.JTextPane txtNombre;
    // End of variables declaration//GEN-END:variables
}
