/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practico4.grupo14;

import clases.*;
import java.util.HashSet;
//ESTEBAN -> MAIN
//TOTO -> ESTETICA, ICONOS 

/**
 *
 * @author Candela Naranjo
 */
public class practico4 extends javax.swing.JFrame {

    /**
     * Creates new form practico4
     */
    public static HashSet<Alumno> listaAlumnos = new HashSet();
    public static HashSet<Materia> listaMaterias = new HashSet();

    public practico4() {
        initComponents();
        //crearMateriasIniciales();
    }

    /*private void crearMateriasIniciales() {
        // 1. Crear las materias: Web 2 (2do), Matemáticas (1ro), Laboratorio 1 (1ro)
        Materia web2 = new Materia(1, "Web 2", 2);
        Materia matematicas = new Materia(2, "Matematicas", 1);
        Materia lab1 = new Materia(3, "Laboratorio 1", 1);

        listaMaterias.add(web2);
        listaMaterias.add(matematicas);
        listaMaterias.add(lab1);

        // 2. Crear 2 alumnos
        Alumno lopez = new Alumno(1001, "Lopez", "Martin");
        Alumno martinez = new Alumno(1002, "Martinez", "Brenda");

        listaAlumnos.add(lopez);
        listaAlumnos.add(martinez);

        // 3. Inscribir a López en las 3 materias
        lopez.agregarMateria(web2);
        lopez.agregarMateria(matematicas);
        lopez.agregarMateria(lab1);

        // 4. Inscribir a Martínez en las 3 materias y volver a inscribirlo en Laboratorio 1
        martinez.agregarMateria(web2);
        martinez.agregarMateria(matematicas);
        martinez.agregarMateria(lab1);
        martinez.agregarMateria(lab1); // Esta no debería agregarse por ser duplicada

        // 5. Visualizar cantidad de materias de cada alumno
        System.out.println("Lopez tiene " + lopez.cantidadMaterias() + " materias");
        System.out.println("Martinez tiene " + martinez.cantidadMaterias() + " materias");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        VistaAlumnos = new javax.swing.JMenu();
        AgregarAlumno = new javax.swing.JMenuItem();
        VistaMaterias = new javax.swing.JMenu();
        AgregarMateria = new javax.swing.JMenuItem();
        VerMateriasCargadas = new javax.swing.JMenuItem();
        VistaInscripcion = new javax.swing.JMenu();
        AgregarInscripcion = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenu();
        SalirDeTodo = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Colegio");

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        VistaAlumnos.setText("Alumno");

        AgregarAlumno.setText("Agregar Alumno");
        AgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarAlumnoActionPerformed(evt);
            }
        });
        VistaAlumnos.add(AgregarAlumno);

        jMenuBar1.add(VistaAlumnos);

        VistaMaterias.setText("Materia");

        AgregarMateria.setText("Agregar Materia");
        AgregarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarMateriaActionPerformed(evt);
            }
        });
        VistaMaterias.add(AgregarMateria);

        VerMateriasCargadas.setText("Ver Materias Cargadas");
        VerMateriasCargadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerMateriasCargadasActionPerformed(evt);
            }
        });
        VistaMaterias.add(VerMateriasCargadas);

        jMenuBar1.add(VistaMaterias);

        VistaInscripcion.setText("Registro");

        AgregarInscripcion.setText("Agregar Inscripción");
        AgregarInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarInscripcionActionPerformed(evt);
            }
        });
        VistaInscripcion.add(AgregarInscripcion);

        jMenuBar1.add(VistaInscripcion);

        Salir.setText("Salir");

        SalirDeTodo.setText("Salir");
        SalirDeTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirDeTodoActionPerformed(evt);
            }
        });
        Salir.add(SalirDeTodo);

        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarMateriaActionPerformed
        // TODO add your handling code here:
        AltadeMaterias materiaFrame = new AltadeMaterias();
        materiaFrame.setLocation((Escritorio.getWidth() - materiaFrame.getWidth()) / 2, (Escritorio.getHeight() - materiaFrame.getHeight()) / 2);
        Escritorio.add(materiaFrame);
        materiaFrame.setVisible(true);
    }//GEN-LAST:event_AgregarMateriaActionPerformed

    private void AgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarAlumnoActionPerformed
        // TODO add your handling code here:
        AltadeAlumnos alumnoFrame = new AltadeAlumnos();
        alumnoFrame.setLocation((Escritorio.getWidth() - alumnoFrame.getWidth()) / 2, (Escritorio.getHeight() - alumnoFrame.getHeight()) / 2);
        Escritorio.add(alumnoFrame);
        alumnoFrame.setVisible(true);
    }//GEN-LAST:event_AgregarAlumnoActionPerformed

    private void AgregarInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarInscripcionActionPerformed
        // TODO add your handling code here:
        FormulariodeInscripcion formularioFrame = new FormulariodeInscripcion();
        formularioFrame.setLocation((Escritorio.getWidth() - formularioFrame.getWidth()) / 2, (Escritorio.getHeight() - formularioFrame.getHeight()) / 2);
        Escritorio.add(formularioFrame);
        formularioFrame.setVisible(true);
    }//GEN-LAST:event_AgregarInscripcionActionPerformed

    private void SalirDeTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirDeTodoActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirDeTodoActionPerformed

    private void VerMateriasCargadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerMateriasCargadasActionPerformed
        // TODO add your handling code here:
        VerMateriasCargadas verMateriasFrame = new VerMateriasCargadas();
        verMateriasFrame.setLocation((Escritorio.getWidth() - verMateriasFrame.getWidth()) / 2,
                (Escritorio.getHeight() - verMateriasFrame.getHeight()) / 2);
        Escritorio.add(verMateriasFrame);
        verMateriasFrame.setVisible(true);
    }//GEN-LAST:event_VerMateriasCargadasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(practico4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(practico4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(practico4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(practico4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new practico4().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarAlumno;
    private javax.swing.JMenuItem AgregarInscripcion;
    private javax.swing.JMenuItem AgregarMateria;
    private javax.swing.JDesktopPane Escritorio;
    private static javax.swing.JMenu Salir;
    private javax.swing.JMenuItem SalirDeTodo;
    private javax.swing.JMenuItem VerMateriasCargadas;
    private static javax.swing.JMenu VistaAlumnos;
    private static javax.swing.JMenu VistaInscripcion;
    private static javax.swing.JMenu VistaMaterias;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
