/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practico4.grupo14;

import clases.*;
import java.util.HashSet;
//ESTEBAN -> MAIN
//TOTO -> ESTETICA, ICONOS 

/**
 *
 * @author Candela Naranjo
 */
public class practico4 extends javax.swing.JFrame {

    /**
     * Creates new form practico4
     */
    public static HashSet<Alumno> listaAlumnos = new HashSet();
    public static HashSet<Materia> listaMaterias = new HashSet();

    public practico4() {
        initComponents();
        //Esteban -> tenes que crear las materias, los alumnoss, inscribirlos y eso, iniciandolos como lo pide en el practico
        //Materias
        Materia web = new Materia(23445,"Web 2",2);
        Materia mat = new Materia(23446,"Matematicas",1);
        Materia lab = new Materia(23447,"Laboratorio 1",1);
        //Alumnos
        Alumno n1 = new Alumno(1001,"Lopez","Martin");
        Alumno n2 = new Alumno(1002,"Martinez","Brenda");
        
        
        listaAlumnos.add(n1);
        listaAlumnos.add(n2);
        
        listaMaterias.add(web);
        listaMaterias.add(mat);
        listaMaterias.add(lab);
       
       
      
       
               

                
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        VistaAlumnos = new javax.swing.JMenu();
        AgregarAlumno = new javax.swing.JMenuItem();
        VerAlumnosCargados = new javax.swing.JMenuItem();
        VistaMaterias = new javax.swing.JMenu();
        AgregarMateria = new javax.swing.JMenuItem();
        VerMateriasCargadas = new javax.swing.JMenuItem();
        VistaInscripcion = new javax.swing.JMenu();
        AgregarInscripcion = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenu();
        SalirDeTodo = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Colegio");

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        VistaAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario (1).png"))); // NOI18N
        VistaAlumnos.setText("Alumno");

        AgregarAlumno.setText("Agregar Alumno");
        AgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarAlumnoActionPerformed(evt);
            }
        });
        VistaAlumnos.add(AgregarAlumno);

        VerAlumnosCargados.setText("Ver Alumnos Cargados");
        VerAlumnosCargados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerAlumnosCargadosActionPerformed(evt);
            }
        });
        VistaAlumnos.add(VerAlumnosCargados);

        jMenuBar1.add(VistaAlumnos);

        VistaMaterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/archivo (3).png"))); // NOI18N
        VistaMaterias.setText("Materia");

        AgregarMateria.setText("Agregar Materia");
        AgregarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarMateriaActionPerformed(evt);
            }
        });
        VistaMaterias.add(AgregarMateria);

        VerMateriasCargadas.setText("Ver Materias Cargadas");
        VerMateriasCargadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerMateriasCargadasActionPerformed(evt);
            }
        });
        VistaMaterias.add(VerMateriasCargadas);

        jMenuBar1.add(VistaMaterias);

        VistaInscripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/archivo (2).png"))); // NOI18N
        VistaInscripcion.setText("Registro");

        AgregarInscripcion.setText("Agregar Inscripción");
        AgregarInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarInscripcionActionPerformed(evt);
            }
        });
        VistaInscripcion.add(AgregarInscripcion);

        jMenuBar1.add(VistaInscripcion);

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/error.png"))); // NOI18N
        Salir.setText("Salir");

        SalirDeTodo.setText("Salir");
        SalirDeTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirDeTodoActionPerformed(evt);
            }
        });
        Salir.add(SalirDeTodo);

        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarMateriaActionPerformed
        // TODO add your handling code here:
        AltadeMaterias materiaFrame = new AltadeMaterias();
        materiaFrame.setLocation((Escritorio.getWidth() - materiaFrame.getWidth()) / 2, (Escritorio.getHeight() - materiaFrame.getHeight()) / 2);
        Escritorio.add(materiaFrame);
        materiaFrame.setVisible(true);
    }//GEN-LAST:event_AgregarMateriaActionPerformed

    private void AgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarAlumnoActionPerformed
        // TODO add your handling code here:
        AltadeAlumnos alumnoFrame = new AltadeAlumnos();
        alumnoFrame.setLocation((Escritorio.getWidth() - alumnoFrame.getWidth()) / 2, (Escritorio.getHeight() - alumnoFrame.getHeight()) / 2);
        Escritorio.add(alumnoFrame);
        alumnoFrame.setVisible(true);
    }//GEN-LAST:event_AgregarAlumnoActionPerformed

    private void AgregarInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarInscripcionActionPerformed
        // TODO add your handling code here:
        FormulariodeInscripcion formularioFrame = new FormulariodeInscripcion();
        formularioFrame.setLocation((Escritorio.getWidth() - formularioFrame.getWidth()) / 2, (Escritorio.getHeight() - formularioFrame.getHeight()) / 2);
        Escritorio.add(formularioFrame);
        formularioFrame.setVisible(true);
    }//GEN-LAST:event_AgregarInscripcionActionPerformed

    private void SalirDeTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirDeTodoActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirDeTodoActionPerformed

    private void VerMateriasCargadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerMateriasCargadasActionPerformed
        // TODO add your handling code here:
        VerMateriasCargadas verMateriasFrame = new VerMateriasCargadas();
        verMateriasFrame.setLocation((Escritorio.getWidth() - verMateriasFrame.getWidth()) / 2,
                (Escritorio.getHeight() - verMateriasFrame.getHeight()) / 2);
        Escritorio.add(verMateriasFrame);
        verMateriasFrame.setVisible(true);
    }//GEN-LAST:event_VerMateriasCargadasActionPerformed

    private void VerAlumnosCargadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerAlumnosCargadosActionPerformed
        // TODO add your handling code here:
       VerAlumnosAgregados verAlumnosFrame = new VerAlumnosAgregados();
       verAlumnosFrame.setLocation((Escritorio.getWidth() - verAlumnosFrame.getWidth())/2,
               (Escritorio.getHeight() - verAlumnosFrame.getHeight())/ 2);
       Escritorio.add(verAlumnosFrame);
       verAlumnosFrame.setVisible(true);
    }//GEN-LAST:event_VerAlumnosCargadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(practico4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(practico4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(practico4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(practico4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new practico4().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarAlumno;
    private javax.swing.JMenuItem AgregarInscripcion;
    private javax.swing.JMenuItem AgregarMateria;
    private javax.swing.JDesktopPane Escritorio;
    private static javax.swing.JMenu Salir;
    private javax.swing.JMenuItem SalirDeTodo;
    private javax.swing.JMenuItem VerAlumnosCargados;
    private javax.swing.JMenuItem VerMateriasCargadas;
    private static javax.swing.JMenu VistaAlumnos;
    private static javax.swing.JMenu VistaInscripcion;
    private static javax.swing.JMenu VistaMaterias;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
