/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package practico4.grupo14;

import clases.Materia;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Candela Naranjo
 */
public class VerMateriasCargadas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VerMateriasCargadas
     */
    public VerMateriasCargadas() {
        initComponents();
        cargarMaterias();
    }

    private void cargarMaterias() {
       DefaultTableModel model = (DefaultTableModel) tablaMaterias.getModel();
        model.setRowCount(0); // Limpiar tabla existente

        if (practico4.listaMaterias.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay materias cargadas en el sistema.", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        } else {
            for (Materia materia : practico4.listaMaterias) {
                model.addRow(new Object[]{
                    materia.getIdMateria(),
                    materia.getNombre(),
                    materia.getAnio()
                });
            }
        }
    }
   
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SalirVerMaterias = new javax.swing.JButton();
        Scroll = new javax.swing.JScrollPane();
        tablaMaterias = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        SalirVerMaterias.setText("Salir");
        SalirVerMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirVerMateriasMouseClicked(evt);
            }
        });
        SalirVerMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirVerMateriasActionPerformed(evt);
            }
        });

        tablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Materia", "Año de la Materia"
            }
        ));
        Scroll.setViewportView(tablaMaterias);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Materias Cargadas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SalirVerMaterias)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SalirVerMaterias)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirVerMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirVerMateriasMouseClicked
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_SalirVerMateriasMouseClicked

    private void SalirVerMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirVerMateriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirVerMateriasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SalirVerMaterias;
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable tablaMaterias;
    // End of variables declaration//GEN-END:variables
}
